# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set the working directory inside the container
WORKDIR /app

# Use bash as the default shell
SHELL ["/bin/bash", "-c"]

# Copy main.py and include directory into the newly created my_project directory
COPY Analysis.py Analysis.py
COPY data data

# Update the system packages and upgrade existing packages
RUN apt-get update && apt-get upgrade -y

# Install graphviz for graph visualization
RUN apt-get install -y graphviz

# Install the Vim text editor
RUN apt-get install -y vim

# Install Python 3 and pip
RUN apt-get install -y python3 python3-pip

# Upgrade pip and install Python dependencies
RUN pip3 install --upgrade pip
RUN pip3 install uproot matplotlib numpy

# Specify to start a bash shell when the container starts
CMD ["/bin/bash"]
